DocumentBase/DocumentBase/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocumentBase.Models;
using NHibernate.Linq;
using NHibernate.Dialect;
using NHibernate.Cfg;
using NHibernate.Driver;
using System.Reflection;
using NHibernate;
using System.Diagnostics;


namespace DocumentBase.Controllers
{
    /// <summary>
    /// Класс для работы с документами
    /// </summary>
    public class DocumentController : Controller
    {      
        /// <summary>
        /// Метод отображающий все документы в хранилище
        /// </summary>
        /// <returns>Список документов</returns>
        public ActionResult IndexAll()
        {
            using (ISession session = NhibernateSession.OpenSession()) 
            {
                IList<Document> documents;
                documents = session.Query<Document>().ToList();
                          
                return View(documents);
            }
        }

        /// <summary>
        /// Метод отображающий документы пользователя
        /// </summary>
        /// <returns>Список документов</returns>
        public ActionResult Index()
        {
            using (ISession session = NhibernateSession.OpenSession())
            {
                IList<Document> documents;
                User user = new User();

                user.id = long.Parse(Session["id"].ToString()); //выбираем авторизованного пользователя в бд
                user.login = Session["Login"].ToString();    
                         
                documents = session.Query<Document>().Where(a => a.author.id == user.id).ToList(); //выборка документов пользователя
                user.Documents = documents;

                return View(documents);
            }                     
        }
       
        /// <summary>
        /// Метод по созданию нового документа
        /// </summary>
        /// <returns>Форма для создания документа</returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Метод создания документа
        /// </summary>
        /// <param name="document">заполненные данные по документу</param>
        /// <param name="fileupload">загруженный документ</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Document document, IEnumerable<HttpPostedFileBase> fileupload)
        {          
                string path = String.Empty;
                document.authorId = long.Parse(Session["id"].ToString());

                using (ISession session = NhibernateSession.OpenSession())
                {
                    foreach (var file in fileupload)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            var extention = System.IO.Path.GetExtension(file.FileName);
                            path = System.IO.Path.Combine(Server.MapPath("~/Files/"), document.name + extention);
                            file.SaveAs(path);
                            var saveQuery = session.GetNamedQuery("FileSaveProcedure");
                            saveQuery.SetParameter("Name", document.name)
                            .SetParameter("authorId", document.authorId)
                            .SetParameter("changedate", document.changeDate)
                            .SetParameter("BinaryFile", path).ExecuteUpdate();

                            return RedirectToAction("IndexAll");
                        }
                        return View("Create");
                    }                   
                }
                return View("Create");
            }
            
        /// <summary>
        /// Метод по поиску документов
        /// </summary>
        /// <param name="sortOrder">порядок сортировки</param>
        /// <param name="searchString">поисковой запрос</param>
        /// <returns></returns>
        public ActionResult Search(string sortOrder, string searchString)
        {
            using (ISession session = NhibernateSession.OpenSession())
            {
                IList<Document> documents;
                IList<User> users;
              
                users = session.Query<User>().ToList();
                documents = session.Query<Document>().ToList();

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : ""; //возможность сортировки по разным столбцам таблицы
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
                ViewBag.AutorSortParm = sortOrder == "Autor" ? "autor_desc" : "Autor";
               
                if (!String.IsNullOrEmpty(searchString))
                {
                    documents = documents.Where(s => s.name.Contains(searchString) || s.authorId.ToString().Contains(searchString)).ToList();
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        documents = documents.OrderByDescending(s => s.name).ToList();
                        break;
                    case "Date":
                        documents = documents.OrderBy(s => s.changeDate).ToList();
                        break;
                    case "date_desc":
                        documents = documents.OrderByDescending(s => s.changeDate).ToList();
                        break;
                    case "autor_desc":
                        documents = documents.OrderByDescending(s => s.author.login).ToList();
                        break;
                    case "Autor":
                        documents = documents.OrderBy(s => s.author.login).ToList();
                        break;
                    default:
                        documents = documents.OrderBy(s => s.changeDate).ToList();
                        break;
                }
                return View(documents);
            }        
        }
        
        /// <summary>
        /// Метод открытия документа
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        public ActionResult Open(string path)
        {
            Process.Start(path);

            return RedirectToAction("Search");
        }

       /// <summary>
       /// Метод по удалению документов из хранилища
       /// </summary>
       /// <param name="id">айди документа</param>
       /// <returns></returns>
        public ActionResult Delete(int id)
        {           
            Document document = new Document();

            using (ISession session = NhibernateSession.OpenSession())
            {
                document = session.Query<Document>().Where(b => b.id == id).FirstOrDefault();
            }
            ViewBag.SubmitAction = "Confirm delete";

            return View("Edit", document);
        }

       /// <summary>
       /// Метод удаления документа из бд
       /// </summary>
       /// <param name="id">айди документа</param>
       /// <param name="collection"></param>
       /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(long id)
        {
            try
            {               
                using (ISession session = NhibernateSession.OpenSession())
                {
                    Document document = session.Get<Document>(id);

                    using (ITransaction trans = session.BeginTransaction())
                    {
                        session.Delete(document);
                        trans.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

    }
}

DocumentBase/DocumentBase/Views/Shared/PartialLoggedin.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>Document Storage</title>

</head>
<body>
    <div style="background-color:forestgreen; width:auto; font-size: 40px">
        <p>
            <b>Document Base for @Session["Login"].ToString()</b> <i class="icon-pencil icon-white"></i>
        </p>
        <a href="@Url.Action("Index", "Document", Model)" class="btn btn-dark btn-md">
            <i class="icon-pencil icon-white"></i>
            <span>
                <strong>Your files</strong>
            </span>
        </a>
        <a href="@Url.Action("IndexAll", "Document", Model)" class="btn btn-dark btn-md">
            <i class="icon-pencil icon-white"></i>
            <span>
                <strong>Inspect all files</strong>
            </span>
        </a>
        <a href="@Url.Action("Search", "Document", Model)" class="btn btn-dark btn-md">
            <i class="icon-pencil icon-white"></i>
            <span>
                <strong>Work with files</strong>
            </span>
        </a>    
        <a href="@Url.Action("Login", "Login", Model)" cla class="btn btn-dark btn-md">
            <i class="icon-pencil icon-white"></i>
            <span>
                <strong>Logout</strong>
            </span>
        </a>                         
</div>
</body>
</html>

DocumentBase/DocumentBase/Views/Shared/PartialView.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    
    <meta name="viewport" content="width=device-width" />
    <title>Document Storage</title>

</head>
<body>
    <div style="background-color:forestgreen; width:auto; font-size: 40px">
        <p>
             <b>Document Base</b> <i class="icon-pencil icon-white"></i> 
            <img src="https://upload.wikimedia.org/wikipedia/ru/thumb/8/8d/Star-Wars-II-still.jpg/200px-Star-Wars-II-still.jpg" width="200" height="135" alt="Hello there!"> 
            <img src="http://www.kitty.hansherman.se/wp-content/uploads/2014/03/Samuel-L-Jackson.jpg" width="200" height="135" alt="Hello there!">
            <img src="https://media.allure.com/photos/5ba532e30ac6c654eca1f789/16:9/w_1280,c_limit/e31a1dd95b519c8063075bf3ebfc231d685e7cd34fb0985dfabe35ab063bdeb84011b71e4ae81ada3b2eb21920dc167c.jpg" width="200" height="135" alt="Hello there!">
            <img src="https://amp.thisisinsider.com/images/5989fc4eefe3df1f008b48b9-750-563.png" width="200" height="135" alt="Hello there!">
            <img src="https://media0ch-a.akamaihd.net/20/99/71504e26ec37f3332b107c91b3ed5e0f.jpeg" width="200" height="135" alt="Hello there!">
             <b>I bid you good fortune</b> <i class="icon-pencil icon-white"></i>
             @*@Html.ActionLink("Login", "Login", "Login")*@
            
        </p>
    </div>
</body>
</html>